name = "grip-props"
version = "0.1.0"
defaultTargets = ["GripProps"]

[leanOptions]
autoImplicit = false

[[lean_lib]]
name = "GripProps"
globs = ["GripProps", "GripProps.+"]

[[require]]
name = "grip"
path = "../"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"
